site_name: HPC Docs
pages:
     - Home: index.md
     - 集群概况: clusterIntro.md
     - 远程连接 *: sshConnection.md
     - 任务系统 *: jobs.md
     - 多机多卡 *: 'distributed.md'
   #   - 框架使用:
   #      - '概要': 'framework/index.md'
   #      - 'chainer': 'framework/chainer.md'
   #      - 'PyTorch': 'framework/pytorch.md'
   #      - 'TensorFlow': 'framework/tensorflow.md'
   #      - 'TensorBoard': 'framework/tensorboard.md'
   #      - 'Caffe': 'framework/caffe.md'
   #      - 'MATLAB': 'framework/matlab.md'
   #      - 'Torch': 'framework/torch.md'
   #   - 注意事项 *: tips.md
     - FAQ *: faq.md
     - 系统监测: systemWatch.md
     - Linux使用:
        - '基础命令': 'linuxBasic/commands.md'
      #   - 'tmux': 'linuxBasic/tmux.md'
      #   - 'gcc': 'linuxBasic/gcc.md'
   #   - 参考资料: refer.md
   #   - 管理员存档:
   #      - '配置记录': 'admin/systemConfigRecord.md'
     - 更新记录: changeLog.md
     - About: about.md
     - 综合楼新配机器: pc.md
theme: readthedocs
markdown_extensions:
    - admonition
